import type { ExplosionConfig, ExplosionType } from "./explosions.types";
import { createSimpleWave } from "./explosions.helpers";
import {
  BROWN_BRICK_DESTROY_WAVE,
  BROWN_BRICK_HIT_WAVE,
  COAL_BRICK_DESTROY_WAVE,
  COAL_BRICK_HIT_WAVE,
  GRAY_BRICK_DESTROY_WAVE_GRADIENT_STOPS,
  GRAY_BRICK_HIT_WAVE_GRADIENT_STOPS,
  GREEN_BRICK_DESTROY_WAVE,
  GREEN_BRICK_HIT_WAVE,
  ICE_BRICK_DESTROY_WAVE,
  ICE_BRICK_HIT_WAVE,
  MAGMA_BRICK_DESTROY_WAVE,
  MAGMA_BRICK_HIT_WAVE,
  ORANGE_BRICK_DESTROY_WAVE,
  ORANGE_BRICK_HIT_WAVE,
  SILVER_BRICK_DESTROY_WAVE,
  SILVER_BRICK_HIT_WAVE,
  YELLOW_BRICK_DESTROY_WAVE,
  YELLOW_BRICK_HIT_WAVE,
} from "./explosions.colors.const";
import {
  GRAY_BRICK_DAMAGE_EMITTER,
  GRAY_BRICK_DESTRUCTION_EMITTER_V2,
  createSolidEmitterFill,
} from "./explosions.emitters.const";

export const BRICK_EXPLOSIONS: Partial<Record<ExplosionType, ExplosionConfig>> = {
  grayBrickHit: {
    lifetimeMs: 1_000,
    defaultInitialRadius: 6,
    waves: createSimpleWave({
      defaultInitialRadius: 6,
      radiusExtension: 40,
      startAlpha: 0.4,
      endAlpha: 0.0,
      gradientStops: GRAY_BRICK_HIT_WAVE_GRADIENT_STOPS,
    }),
    emitter: GRAY_BRICK_DAMAGE_EMITTER,
  },
  grayBrickDestroy: {
    lifetimeMs: 1_200,
    defaultInitialRadius: 10,
    waves: createSimpleWave({
      defaultInitialRadius: 10,
      radiusExtension: 60,
      startAlpha: 0.6,
      endAlpha: 0.0,
      gradientStops: GRAY_BRICK_DESTROY_WAVE_GRADIENT_STOPS,
    }),
    emitter: GRAY_BRICK_DESTRUCTION_EMITTER_V2,
  },
  grayBrickDestroyV2: {
    lifetimeMs: 1_200,
    defaultInitialRadius: 10,
    waves: createSimpleWave({
      defaultInitialRadius: 10,
      radiusExtension: 60,
      startAlpha: 0.5,
      endAlpha: 0.0,
      gradientStops: GRAY_BRICK_DESTROY_WAVE_GRADIENT_STOPS,
    }),
    emitter: GRAY_BRICK_DESTRUCTION_EMITTER_V2,
  },
  yellowBrickHit: {
    lifetimeMs: 1_000,
    defaultInitialRadius: 6,
    waves: createSimpleWave({
      defaultInitialRadius: 6,
      radiusExtension: 40,
      startAlpha: 0.6,
      endAlpha: 0,
      gradientStops: YELLOW_BRICK_HIT_WAVE,
    }),
    emitter: {
      ...GRAY_BRICK_DAMAGE_EMITTER,
      color: { r: 1, g: 0.95, b: 0.6, a: 1 },
      fill: createSolidEmitterFill({ r: 0.9, g: 0.85, b: 0.5, a: 1 }),
    },
  },
  yellowBrickDestroy: {
    lifetimeMs: 1_200,
    defaultInitialRadius: 10,
    waves: createSimpleWave({
      defaultInitialRadius: 10,
      radiusExtension: 60,
      startAlpha: 0.7,
      endAlpha: 0,
      gradientStops: YELLOW_BRICK_DESTROY_WAVE,
    }),
    emitter: {
      ...GRAY_BRICK_DESTRUCTION_EMITTER_V2,
      color: { r: 1, g: 0.95, b: 0.6, a: 1 },
      fill: createSolidEmitterFill({ r: 0.8, g: 0.75, b: 0.4, a: 1 }),
    },
  },
  organicBrickHit: {
    lifetimeMs: 1_000,
    defaultInitialRadius: 6,
    waves: createSimpleWave({
      defaultInitialRadius: 6,
      radiusExtension: 30,
      startAlpha: 0.6,
      endAlpha: 0,
      gradientStops: GREEN_BRICK_HIT_WAVE,
    }),
    emitter: {
      ...GRAY_BRICK_DAMAGE_EMITTER,
      color: { r: 0.6, g: 1, b: 0.7, a: 1 },
      fill: createSolidEmitterFill({ r: 0.6, g: 1, b: 0.7, a: 1 }),
    },
  },
  organicBrickDestroy: {
    lifetimeMs: 1_200,
    defaultInitialRadius: 10,
    waves: createSimpleWave({
      defaultInitialRadius: 10,
      radiusExtension: 50,
      startAlpha: 0.7,
      endAlpha: 0,
      gradientStops: GREEN_BRICK_DESTROY_WAVE,
    }),
    emitter: {
      ...GRAY_BRICK_DESTRUCTION_EMITTER_V2,
      color: { r: 0.6, g: 1, b: 0.7, a: 1 },
      fill: createSolidEmitterFill({ r: 0.3, g: 0.8, b: 0.2, a: 1 }),
    },
  },
  ironBrickHit: {
    lifetimeMs: 1_000,
    defaultInitialRadius: 6,
    waves: createSimpleWave({
      defaultInitialRadius: 6,
      radiusExtension: 30,
      startAlpha: 0.6,
      endAlpha: 0,
      gradientStops: ORANGE_BRICK_HIT_WAVE,
    }),
    emitter: {
      ...GRAY_BRICK_DAMAGE_EMITTER,
      color: { r: 1, g: 0.8, b: 0.55, a: 1 },
      fill: createSolidEmitterFill({ r: 1, g: 0.8, b: 0.55, a: 1 }),
    },
  },
  ironBrickDestroy: {
    lifetimeMs: 1_200,
    defaultInitialRadius: 10,
    waves: createSimpleWave({
      defaultInitialRadius: 10,
      radiusExtension: 50,
      startAlpha: 0.7,
      endAlpha: 0,
      gradientStops: ORANGE_BRICK_DESTROY_WAVE,
    }),
    emitter: {
      ...GRAY_BRICK_DESTRUCTION_EMITTER_V2,
      color: { r: 1, g: 0.8, b: 0.55, a: 1 },
      fill: createSolidEmitterFill({ r: 1, g: 0.8, b: 0.55, a: 1 }),
    },
  },
  woodBrickHit: {
    lifetimeMs: 1_000,
    defaultInitialRadius: 6,
    waves: createSimpleWave({
      defaultInitialRadius: 6,
      radiusExtension: 30,
      startAlpha: 0.6,
      endAlpha: 0,
      gradientStops: BROWN_BRICK_HIT_WAVE,
    }),
    emitter: {
      ...GRAY_BRICK_DAMAGE_EMITTER,
      color: { r: 0.75, g: 0.55, b: 0.35, a: 1 },
      fill: createSolidEmitterFill({ r: 0.9, g: 0.75, b: 0.45, a: 1 }),
    },
  },
  woodBrickDestroy: {
    lifetimeMs: 1_200,
    defaultInitialRadius: 10,
    waves: createSimpleWave({
      defaultInitialRadius: 10,
      radiusExtension: 50,
      startAlpha: 0.8,
      endAlpha: 0,
      gradientStops: BROWN_BRICK_DESTROY_WAVE,
    }),
    emitter: {
      ...GRAY_BRICK_DESTRUCTION_EMITTER_V2,
      color: { r: 0.75, g: 0.55, b: 0.35, a: 1 },
      fill: createSolidEmitterFill({ r: 0.9, g: 0.75, b: 0.45, a: 1 }),
    },
  },
  copperBrickHit: {
    lifetimeMs: 1_000,
    defaultInitialRadius: 6,
    waves: createSimpleWave({
      defaultInitialRadius: 6,
      radiusExtension: 30,
      startAlpha: 0.5,
      endAlpha: 0,
      gradientStops: ORANGE_BRICK_HIT_WAVE,
    }),
    emitter: {
      ...GRAY_BRICK_DAMAGE_EMITTER,
      color: { r: 0.95, g: 0.65, b: 0.35, a: 1 },
      fill: createSolidEmitterFill({ r: 0.95, g: 0.75, b: 0.55, a: 1 }),
    },
  },
  copperBrickDestroy: {
    lifetimeMs: 1_200,
    defaultInitialRadius: 10,
    waves: createSimpleWave({
      defaultInitialRadius: 10,
      radiusExtension: 50,
      startAlpha: 0.7,
      endAlpha: 0,
      gradientStops: ORANGE_BRICK_DESTROY_WAVE,
    }),
    emitter: {
      ...GRAY_BRICK_DESTRUCTION_EMITTER_V2,
      color: { r: 0.95, g: 0.65, b: 0.35, a: 1 },
      fill: createSolidEmitterFill({ r: 0.95, g: 0.75, b: 0.55, a: 1 }),
    },
  },
  silverBrickHit: {
    lifetimeMs: 1_000,
    defaultInitialRadius: 6,
    waves: createSimpleWave({
      defaultInitialRadius: 6,
      radiusExtension: 30,
      startAlpha: 0.6,
      endAlpha: 0,
      gradientStops: SILVER_BRICK_HIT_WAVE,
    }),
    emitter: {
      ...GRAY_BRICK_DAMAGE_EMITTER,
      color: { r: 0.92, g: 0.93, b: 0.96, a: 1 },
      fill: createSolidEmitterFill({ r: 0.72, g: 0.93, b: 0.96, a: 1 }),
    },
  },
  silverBrickDestroy: {
    lifetimeMs: 1_200,
    defaultInitialRadius: 10,
    waves: createSimpleWave({
      defaultInitialRadius: 10,
      radiusExtension: 50,
      startAlpha: 0.8,
      endAlpha: 0,
      gradientStops: SILVER_BRICK_DESTROY_WAVE,
    }),
    emitter: {
      ...GRAY_BRICK_DESTRUCTION_EMITTER_V2,
      color: { r: 0.92, g: 0.93, b: 0.96, a: 1 },
      fill: createSolidEmitterFill({ r: 0.72, g: 0.93, b: 0.96, a: 1 }),
    },
  },
  coalBrickHit: {
    lifetimeMs: 1_000,
    defaultInitialRadius: 6,
    waves: createSimpleWave({
      defaultInitialRadius: 6,
      radiusExtension: 30,
      startAlpha: 0.6,
      endAlpha: 0,
      gradientStops: COAL_BRICK_HIT_WAVE,
    }),
    emitter: {
      ...GRAY_BRICK_DAMAGE_EMITTER,
      color: { r: 0.24, g: 0.24, b: 0.27, a: 1 },
      fill: createSolidEmitterFill({ r: 0.24, g: 0.24, b: 0.27, a: 1 }),
    },
  },
  coalBrickDestroy: {
    lifetimeMs: 1_200,
    defaultInitialRadius: 10,
    waves: createSimpleWave({
      defaultInitialRadius: 10,
      radiusExtension: 50,
      startAlpha: 0.8,
      endAlpha: 0,
      gradientStops: COAL_BRICK_DESTROY_WAVE,
    }),
    emitter: {
      ...GRAY_BRICK_DESTRUCTION_EMITTER_V2,
      color: { r: 0.24, g: 0.24, b: 0.27, a: 1 },
      fill: createSolidEmitterFill({ r: 0.24, g: 0.24, b: 0.27, a: 1 }),
    },
  },
  iceBrickHit: {
    lifetimeMs: 1_000,
    defaultInitialRadius: 6,
    waves: createSimpleWave({
      defaultInitialRadius: 6,
      radiusExtension: 30,
      startAlpha: 0.6,
      endAlpha: 0,
      gradientStops: ICE_BRICK_HIT_WAVE,
    }),
    emitter: {
      ...GRAY_BRICK_DAMAGE_EMITTER,
      color: { r: 0.7, g: 0.9, b: 1.0, a: 1 },
      fill: createSolidEmitterFill({ r: 0.7, g: 0.9, b: 1.0, a: 1 }),
    },
  },
  iceBrickDestroy: {
    lifetimeMs: 1_200,
    defaultInitialRadius: 10,
    waves: createSimpleWave({
      defaultInitialRadius: 10,
      radiusExtension: 50,
      startAlpha: 0.8,
      endAlpha: 0,
      gradientStops: ICE_BRICK_DESTROY_WAVE,
    }),
    emitter: {
      ...GRAY_BRICK_DESTRUCTION_EMITTER_V2,
      color: { r: 0.85, g: 0.95, b: 1.0, a: 1 },
      fill: createSolidEmitterFill({ r: 0.85, g: 0.95, b: 1.0, a: 1 }),
    },
  },
  magmaBrickHit: {
    lifetimeMs: 1_000,
    defaultInitialRadius: 6,
    waves: createSimpleWave({
      defaultInitialRadius: 6,
      radiusExtension: 30,
      startAlpha: 0.6,
      endAlpha: 0,
      gradientStops: MAGMA_BRICK_HIT_WAVE,
    }),
    emitter: {
      ...GRAY_BRICK_DAMAGE_EMITTER,
      color: { r: 1.0, g: 0.5, b: 0.15, a: 1 },
      fill: createSolidEmitterFill({ r: 1.0, g: 0.5, b: 0.15, a: 1 }),
    },
  },
  magmaBrickDestroy: {
    lifetimeMs: 1_200,
    defaultInitialRadius: 10,
    waves: createSimpleWave({
      defaultInitialRadius: 10,
      radiusExtension: 50,
      startAlpha: 0.8,
      endAlpha: 0,
      gradientStops: MAGMA_BRICK_DESTROY_WAVE,
    }),
    emitter: {
      ...GRAY_BRICK_DESTRUCTION_EMITTER_V2,
      color: { r: 1.0, g: 0.65, b: 0.2, a: 1 },
      fill: createSolidEmitterFill({ r: 1.0, g: 0.65, b: 0.2, a: 1 }),
    },
  },
};
