export const DEFAULT_PHEROMONE_IDLE_THRESHOLD_SECONDS = 2;
export const DEFAULT_PHEROMONE_BUFF_ATTACKS = 4;
export const DEFAULT_MENDING_HEALS_PER_RUN = 10;
export const HEAL_SKIP_RATIO_THRESHOLD = 0.6;
export const PHEROMONE_HEAL_EXPLOSION_RADIUS = 14;
export const PHEROMONE_FRENZY_EXPLOSION_RADIUS = 12;
